IF (WIN32)
    set(ZLIB_INCLUDE_DIRS "${THIRDPARTY_LIB_DIR}/zlib/include")
    set(ZLIB_LIBRARY "${THIRDPARTY_LIB_DIR}/zlib/lib/zlib.lib")
    list(APPEND CMAKE_PREFIX_PATH ${ZLIB_INCLUDE_DIRS} ${ZLIB_LIBRARY})
ELSE ()
    
ENDIF ()
