IF (WIN32)
    # set(LIBLUA_DIR ${THIRDPARTY_LIB_DIR}/lua)
    # list(APPEND CMAKE_PREFIX_PATH ${LIBLUA_DIR})
    set(LUA_INCLUDE_DIR ${THIRDPARTY_LIB_DIR}/lua/include)
    set(LUA_LIBRARIES ${THIRDPARTY_LIB_DIR}/lua/lib/lua5.1.lib)
    list(APPEND CMAKE_PREFIX_PATH ${LUA_INCLUDE_DIR} ${LUA_LIBRARIES})
ELSE ()
    
ENDIF ()
