IF (WIN32)
    set(LIBPROTOBUF_DIR ${THIRDPARTY_LIB_DIR}/protobuf)
    list(APPEND CMAKE_PREFIX_PATH ${LIBPROTOBUF_DIR})
    message("Find Protobuf : ${LIBPROTOBUF_DIR}")
    # set(Protobuf_INCLUDE_DIR ${LIBPROTOBUF_DIR}/include)
    # set(Protobuf_LIBRARY_DEBUG ${LIBPROTOBUF_DIR}/lib/libprotobufd.lib)
    # set(Protobuf_LIBRARY_RELEASE ${LIBPROTOBUF_DIR}/lib/libprotobuf.lib)
    # set(Protobuf_LITE_LIBRARY_DEBUG ${LIBPROTOBUF_DIR}/lib/libprotobuf-lited.lib)
    # set(Protobuf_LITE_LIBRARY_RELEASE ${LIBPROTOBUF_DIR}/lib/libprotobuf-lite.lib)
    # set(Protobuf_PROTOC_LIBRARY_DEBUG ${LIBPROTOBUF_DIR}/lib/libprotocd.lib)
    # set(Protobuf_PROTOC_LIBRARY_RELEASE ${LIBPROTOBUF_DIR}/lib/libprotoc.lib)
    # set(Protobuf_PROTOC_EXECUTABLE ${LIBPROTOBUF_DIR}/bin/protoc.exe)
    # list(APPEND CMAKE_PREFIX_PATH ${LIBPROTOBUF_DIR} ${Protobuf_INCLUDE_DIR} ${Protobuf_LIBRARY_DEBUG} ${Protobuf_LIBRARY_RELEASE} ${Protobuf_LITE_LIBRARY_DEBUG} ${Protobuf_LITE_LIBRARY_RELEASE} ${Protobuf_PROTOC_LIBRARY_DEBUG} ${Protobuf_PROTOC_LIBRARY_RELEASE} ${Protobuf_PROTOC_EXECUTABLE})
    # message("Find Protobuf : ${LIBPROTOBUF_DIR} ${Protobuf_INCLUDE_DIR} ${Protobuf_LIBRARY_DEBUG} ${Protobuf_LIBRARY_RELEASE} ${Protobuf_LITE_LIBRARY_DEBUG} ${Protobuf_LITE_LIBRARY_RELEASE} ${Protobuf_PROTOC_LIBRARY_DEBUG} ${Protobuf_PROTOC_LIBRARY_RELEASE} ${Protobuf_PROTOC_EXECUTABLE}")    
ENDIF ()

find_package(Protobuf REQUIRED)
